# Generated by Django 4.1.4 on 2022-12-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(choices=[('GZ', 'Gz'), ('ULK', 'Ulk'), ('LT', 'Lt'), ('E', 'E'), ('SM', 'Sm'), ('MT', 'Mt'), ('MF', 'Mf'), ('FV', 'Fv')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudyStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('specialty', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=255)),
                ('forename', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('study_streams', models.ManyToManyField(to='schedule_db_api.studystream')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_db_api.studystream')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lesson_type', models.TextField(choices=[('LAB', 'Lab'), ('SEM', 'Sem'), ('LEC', 'Lec'), ('PRACTICE', 'Practice'), ('PHYSICAL', 'Physical')], max_length=8)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_db_api.place')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule_db_api.subject')),
                ('teacher', models.ManyToManyField(null=True, to='schedule_db_api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_db_api.studystream')),
            ],
        ),
    ]
