# Generated by Django 4.1.4 on 2022-12-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_generic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('faculty', models.CharField(max_length=255)),
                ('study_level', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('POSTGRADUATE', 'Postgragudate'), ('SPECIALIST', 'Specialist')], max_length=12)),
                ('semester_start', models.DateField()),
                ('semester_end', models.DateField()),
            ],
            options={
                'unique_together': {('semester', 'faculty', 'study_level')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('study_streams', models.ManyToManyField(to='schedule_db_api.studystream')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_db_api.studystream')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pair_num', models.IntegerField()),
                ('lesson_type', models.TextField(choices=[('LAB', 'Lab'), ('SEM', 'Sem'), ('LEC', 'Lec'), ('PRACTICE', 'Practice'), ('PHYSICAL', 'Physical'), ('VUC', 'Vuc')], max_length=8)),
                ('groups', models.ManyToManyField(to='schedule_db_api.group')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_db_api.place')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_db_api.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_db_api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_db_api.studystream'),
        ),
    ]
