# Generated by Django 4.1.4 on 2022-12-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_db_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(to='schedule_db_api.teacher'),
        ),
    ]
