# Generated by Django 4.1.4 on 2022-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_db_api', '0002_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(to='schedule_db_api.group'),
        ),
    ]
