# Generated by Django 4.1.4 on 2022-12-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_db_api', '0003_lesson_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
